//
//  RepositoryListModels.swift
//  GitCleanSwift
//
//  Created by Mauricio Balena Mazzocco on 06/07/20.
//  Copyright (c) 2020 Mauricio Balena Mazzocco. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum RepositoryList {
    // MARK: Use cases
    enum FetchRepositories {
        struct Request {
            var isReloading: Bool
        }
        struct Response {
            var repositories: [Repository]
            var hasNext: Bool
            var isReloading: Bool
        }
        struct ViewModel {
            struct DisplayedRepository {
                var repoName: String
                var userAvatarPath: String?
                var repoStarsCount: String
                var userProfilePath: String?
            }
            var displayedRepositories: [DisplayedRepository]
            var isReloading: Bool
            var hasNext: Bool
        }
    }

    enum Error {
        struct Response {
            var serviceError: ServiceError
        }

        struct ViewModel {
            var errorString: String
        }
    }
}
